### ISSUE TITLE
MAILOSAUR_TIMEOUT cannot be set (ENV vars are strings in Ruby)

### ISSUE THREAD

**Issue by tk8817** [mailosaurapp/mailosaur-ruby#10]
Hey folks, 

so we are trying to reduce the timeout in Mailosaur but we noticed that it is not possible in the current design.

Your code: 
```ruby
@timeout  = ENV['MAILOSAUR_TIMEOUT'] || 20
```

in Ruby ENV vars are always strings, it will not allow you to set it to an int 
```ruby
ENV['MAILOSAUR_TIMEOUT'] = 1
```
Results in this error
```ruby
no implicit conversion of Fixnum into String (TypeError)
/Users/jcommu/Development/bueller_cc/features/support/env.rb:26:in `[]='
/Users/jcommu/Development/bueller_cc/features/support/env.rb:26:in `<top (required)>'
```

And setting it to a string results in an error on your side. 

```ruby
ENV['MAILOSAUR_TIMEOUT'] = "1"
```

```ruby
    Then I should receive a {registration} email
      undefined method `zero?' for "1":String (NoMethodError)
      ./features/step_defenitions/mailosaur_steps.rb:7:in `block (2 levels) in <top (required)>'
      ./features/step_defenitions/mailosaur_steps.rb:6:in `times'
      ./features/step_defenitions/mailosaur_steps.rb:6:in `/^I should receive (?:a|an) {(email_updated|forgot_password|registration)} email$/'
      features/tests/tmp.feature:5:in `Then I should receive a {registration} email'
```

I have made 2 PR's to fix this.

#11 is a quick-fix that keeps ENV['MAILOSAUR_TIMEOUT'] in play and simply converts it to an int.
#12 is a better long term fix which removes the ENV var and takes the input on object creation.

```ruby
mailbox    = Mailosaur.new(mailbox, api_key, timeout)
```

**Comment by tk8817** [comment]
See #11 , however this should really be solved in the long-term by passing timeout during Mailosaur initialization.

```ruby
mailbox    = Mailosaur.new(mailbox, api_key, timeout)
```

**Comment by tk8817** [comment]
See #12 for the long-term fix

**Comment by tk8817** [comment]
@mailosaurapp closing this as it is fixed with the most recent merge.
