### ISSUE TITLE
TypeError on getEmails() 

### ISSUE THREAD

**Issue by dmhalejr** [mailosaurapp/mailosaur-ruby#2]
Receiving the below error when attempting getEmails() with or without a string. 
```
TypeError: no implicit conversion of Fixnum into String
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/mailosaur-0.0.12/lib/mailosaur.rb:41:in `+'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/mailosaur-0.0.12/lib/mailosaur.rb:41:in `block in getEmails'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/mailosaur-0.0.12/lib/mailosaur.rb:33:in `each'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/mailosaur-0.0.12/lib/mailosaur.rb:33:in `getEmails'
	from (irb):3
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

Let me know if you need anything else.

**Comment by AMailosaur** [comment]
Hi David,

This bug should now be fixed and a new gem 0.0.0.14 has been published.

Let me know if you encounter any issues.

Thanks
